[package]

name = "pip_app"
version = "0.1.0"
authors = ["thecharlesblake <thecharlesblake@live.co.uk>"]

[dependencies]

pip_core = { path = "../pip_core" }
clap = {version = "2.32", features = ["yaml"]}
petgraph = "0.4"