[package]

name = "pip_core"
version = "0.1.0"
authors = ["thecharlesblake <thecharlesblake@live.co.uk>"]

[dependencies]

regex = "1"
itertools = "0.7.11"
serde = "1.0.80"
serde_derive = "1.0.80"
serde_yaml = "0.8.6"
lazy_static = "1.1.0"
bimap = "0.1.5"